import {
    Button,
    VerticalBox,
    Palette,
    HorizontalBox,
    ScrollView,
} from "std-widgets.slint";
import { Style } from "../style.slint";
import { ToolButton } from "tool_button.slint";

export component TabButton inherits Rectangle {
    in property <string> tab-text;
    in property <bool> is-selected: false;
    callback clicked <=> ta.clicked;
    background: is-selected ? Style.palette.background.brighter(0.1) : Style.palette.background.darker(0.1);
    border-width: Style.size.border-width;
    border-color: Palette.border;
    inner-rect := Rectangle {
        states [
            active-hover when ta.has-hover && !root.is-selected: {
                inner-rect.background: Style.palette.hover;
            }
        ]
        VerticalLayout {
            padding-left: Style.size.spacing * 2;
            padding-right: Style.size.spacing * 2;
            padding-top: Style.size.spacing;
            padding-bottom: Style.size.spacing;
            text-label := Text {
                vertical-alignment: center;
                horizontal-alignment: center;
                text: tab-text;
            }

            Rectangle {
                height: Style.size.border-width;
                states [
                    active_text when root.is-selected: {
                        color: Palette.selection-background;
                    }
                ]
            }
        }
    }

    ta := TouchArea { }
}

export component TabCreateButton inherits Rectangle {
    callback clicked <=> ta.clicked;
    background: Style.palette.background.darker(0.1);
    border-width: Style.size.border-width;
    border-color: Palette.border;
    inner-rect := Rectangle {
        states [
            active-hover when ta.has-hover: {
                inner-rect.background: Style.palette.hover;
            }
        ]
        Image {
            vertical-alignment: center;
            width: Style.size.image_width;
            source: @image-url("../../assets/icons/add2.svg");
            colorize: Palette.foreground;
        }
    }

    ta := TouchArea { }
}

export component TabImageButton inherits Rectangle {
    in property <image> image_source;
    in property <bool> is-selected: false;
    callback clicked <=> ta.clicked;
    background: is-selected ? Style.palette.background.brighter(0.1) : Style.palette.background.darker(0.1);
    border-width: Style.size.border-width;
    border-color: Palette.border;
    states [
        active_selected when root.is-selected: {
            border-color: Palette.selection-background;
        }
    ]
    inner-rect := Rectangle {
        states [
            active-hover when ta.has-hover && !root.is-selected: {
                inner-rect.background: Style.palette.hover;
            }
        ]
        Image {
            vertical-alignment: center;
            width: Style.size.image_width;
            source: root.image_source;
            colorize: Palette.foreground;
        }
    }

    ta := TouchArea { }
}

component TabSettingsButton inherits Rectangle {
    callback clicked <=> ta.clicked;
    border-width: Style.size.border-width;
    border-color: Palette.border;
    width: 40px;
    states [
        active-hover when ta.has-hover: {
            background: Style.palette.hover;
        }
    ]
    Image {
        vertical-alignment: center;
        width: Style.size.image_width;
        source: @image-url("../../assets/icons/settings.svg");
        colorize: Palette.foreground;
    }

    ta := TouchArea { }
}

export component TabViewItem inherits Rectangle {
    in property <int> current-index;
    in property <int> index;
    out property <bool> is_active: root.current-index == root.index;
    visible: index == current-index;
    background: is_active ? Style.palette.background.brighter(0.1) : Style.palette.background.darker(0.1);
}

export component TabView inherits Rectangle {
    in property <[string]> model;
    in property <bool> create_button_enabled: true;
    in property <bool> hide_button_enable: false;
    in property <length> layout_padding: 5px;
    in property <bool> settings_button_enabled: false;
    in property <LayoutAlignment> alignment: start;
    in property <length> max_child_width;
    out property <int> current-index;
    callback request-create();
    callback request-open-settings();
    callback request-hide();
    callback request-show();
    public function set_current_index(index: int) {
        root.current-index = index;
    }
    border-width: Style.size.border-width;
    border-color: Palette.border;
    preferred-width: Math.max(max_child_width, tab-button-layout.preferred-width) + 20px;

    HorizontalLayout {
        padding-right: root.hide_button_enable ? 5px : 0px;
        tab-button-layout := VerticalLayout {
            padding: root.layout_padding;
            HorizontalLayout {
                height: Style.size.control-height;
                ScrollView {
                    horizontal-scrollbar-policy: always-off;
                    vertical-scrollbar-policy: always-off;
                    HorizontalLayout {
                        alignment: root.alignment;
                        for tab_text[idx] in root.model: TabButton {
                            tab-text: tab_text;
                            is-selected: current-index == idx;
                            clicked => {
                                root.current-index = idx;
                            }
                        }
                        if (root.create_button_enabled): TabCreateButton {
                            width: Style.size.control-small-width;
                            clicked => {
                                root.request-create();
                            }
                        }
                    }
                }

                if (root.settings_button_enabled): TabSettingsButton {
                    clicked => {
                        root.request-open-settings();
                    }
                }
            }

            Rectangle {
                @children
            }
        }

        if root.hide_button_enable: Rectangle {
            width: Style.size.image_width;
            Image {
                source: @image-url("../../assets/icons/to_left.svg");
                colorize: Palette.foreground;
                width: Style.size.image_width;
            }

            states [
                has_active_hover when ta.has-hover: {
                    background: Style.palette.background.darker(0.2);
                }
            ]
            ta := TouchArea {
                clicked => {
                    root.request-hide();
                }
            }
        }
    }
}

export component CenterTabView inherits Rectangle {
    in property <[image]> image_model;
    in property <length> layout_padding: 5px;
    in property <length> spacing: 0px;
    out property <int> current-index;
    callback request-create();
    callback request-open-settings();
    public function set_current_index(index: int) {
        root.current-index = index;
    }
    border-width: Style.size.border-width;
    border-color: Palette.border;
    VerticalLayout {
        padding: root.layout_padding;
        Rectangle {
            height: Style.size.control-height;
            HorizontalLayout {
                alignment: center;
                if root.image_model.length > 0: ScrollView {
                    preferred-width: Style.size.tab-button-width * root.image_model.length + root.image_model.length * root.spacing;
                    horizontal-scrollbar-policy: always-off;
                    vertical-scrollbar-policy: always-off;
                    HorizontalLayout {
                        alignment: center;
                        spacing: root.spacing;
                        for image[idx] in root.image_model: TabImageButton {
                            height: Style.size.control-height;
                            width: Style.size.control-small-width;
                            image_source: image;
                            is-selected: current-index == idx;
                            clicked => {
                                root.current-index = idx;
                            }
                        }
                    }
                }
            }
        }

        Rectangle {
            @children
        }
    }
}
