import {
    Button,
    VerticalBox,
    Palette,
    HorizontalBox,
    ScrollView,
} from "std-widgets.slint";
import { Style } from "../style.slint";
import { ToolButton } from "tool_button.slint";

component TabButton inherits Rectangle {
    in property <string> tab-text;
    in property <bool> is-selected: false;
    callback clicked <=> ta.clicked;
    height: Style.size.control-height;
    width: Style.size.tab-button-width;
    background: is-selected ? Style.palette.background.brighter(0.1) : Style.palette.background.darker(0.1);
    border-width: Style.size.border-width;
    border-color: Palette.border;
    inner-rect := Rectangle {
        height: parent.height - Style.size.spacing * 2;
        width: parent.width - Style.size.spacing * 2;
        states [
            active-hover when ta.has-hover && !root.is-selected: {
                inner-rect.background: Style.palette.hover;
            }
        ]
        Text {
            vertical-alignment: center;
            text: is-selected ? "« " + tab-text + " »" : tab-text;
        }
    }

    ta := TouchArea { }
}

component TabCreateButton inherits Rectangle {
    callback clicked <=> ta.clicked;
    background: Style.palette.background.darker(0.1);
    border-width: Style.size.border-width;
    border-color: Palette.border;
    inner-rect := Rectangle {
        height: parent.height - Style.size.spacing * 2;
        width: parent.width - Style.size.spacing * 2;
        states [
            active-hover when ta.has-hover: {
                inner-rect.background: Style.palette.hover;
            }
        ]
        Image {
            vertical-alignment: center;
            width: Style.size.image_width;
            source: @image-url("../../assets/icons/add2.svg");
            colorize: Palette.foreground;
        }
    }

    ta := TouchArea { }
}

component TabSettingsButton inherits Rectangle {
    callback clicked <=> ta.clicked;
    border-width: Style.size.border-width;
    border-color: Palette.border;
    width: 40px;
    states [
        active-hover when ta.has-hover: {
            background: Style.palette.hover;
        }
    ]
    Image {
        vertical-alignment: center;
        width: Style.size.image_width;
        source: @image-url("../../assets/icons/settings.svg");
        colorize: Palette.foreground;
    }

    ta := TouchArea { }
}

export component TabViewItem inherits Rectangle {
    in property <int> current-index;
    in property <int> index;
    out property <bool> is_active: root.current-index == root.index;
    visible: index == current-index;
    background: is_active ? Style.palette.background.brighter(0.1) : Style.palette.background.darker(0.1);
}

export component TabView inherits Rectangle {
    in property <[string]> model;
    in property <bool> create_button_enabled: true;
    in property <length> layout_padding: 5px;
    in property <bool> settings_button_enabled: false;
    out property <int> current-index;
    callback request-create();
    callback request-open-settings();
    public function set_current_index(index: int) {
        root.current-index = index;
    }
    border-width: Style.size.border-width;
    border-color: Palette.border;
    VerticalLayout {
        alignment: stretch;
        padding: root.layout_padding;
        Rectangle {
            height: Style.size.control-height;
            HorizontalLayout {
                alignment: space-between;
                HorizontalLayout {
                    alignment: start;
                    if root.model.length > 0: ScrollView {
                        preferred-width: Style.size.tab-button-width * root.model.length;
                        horizontal-scrollbar-policy: always-off;
                        vertical-scrollbar-policy: always-off;
                        HorizontalLayout {
                            alignment: start;
                            for tab_text[idx] in root.model: TabButton {
                                tab-text: tab_text;
                                is-selected: current-index == idx;
                                clicked => {
                                    root.current-index = idx;
                                }
                            }
                        }
                    }
                    if (root.create_button_enabled): TabCreateButton {
                        height: Style.size.control-height;
                        width: Style.size.control-small-width;
                        clicked => {
                            root.request-create();
                        }
                    }
                }

                if (root.settings_button_enabled): TabSettingsButton {
                    clicked => {
                        root.request-open-settings();
                    }
                }
            }
        }

        Rectangle {
            @children
        }
    }
}
