import { Popup } from "popup.slint";
import { Style } from "style.slint";
import { SlintReviewHelperSettings, SlintModelUtils } from "globals.slint";
import { ToolButton } from "tool_button.slint";

import {
    VerticalBox,
    LineEdit,
    Button,
    ComboBox,
    Palette,
} from "std-widgets.slint";


export component AppConfigPopup inherits Popup {
    title: "Config";

    VerticalBox {
        alignment: space-between;

        GridLayout {
            spacing: Style.size.spacing;

            Row {
                Text {
                    font-size: Style.font.config-edit;
                    vertical-alignment: center;
                    text: "diff tool";
                }

                ComboBox {
                    private property <int> difftool_idx: SlintReviewHelperSettings.difftool_index;
                    changed difftool_idx => {
                        self.current-index = difftool_idx
                    }
                    current-value: SlintReviewHelperSettings.diff_tool;
                    model: SlintReviewHelperSettings.diff_tool_model;
                    selected(current-value) => {
                        SlintReviewHelperSettings.difftool_index = SlintModelUtils.index_of_string(SlintReviewHelperSettings.diff_tool_model, current-value);
                        SlintReviewHelperSettings.diff_tool = current-value;
                    }
                }

                ToolButton {
                    source: @image-url("../assets/icons/refresh.svg");
                    clicked => {
                        SlintReviewHelperSettings.refresh_diff_tool_model()
                    }
                }
            }

            Row {
                Text {
                    font-size: Style.font.config-edit;
                    vertical-alignment: center;
                    text: "editor";
                }

                editor_edit := LineEdit {
                    height: Style.size.control_height;
                    text <=> SlintReviewHelperSettings.editor;
                }
            }

            Row {
                Text {
                    font-size: Style.font.config-edit;
                    vertical-alignment: center;
                    text: "editor args";
                }

                editor_args_edit := LineEdit {
                    height: Style.size.control_height;
                    text <=> SlintReviewHelperSettings.editor_args;
                }
            }

            Row {
                Text {
                    font-size: Style.font.config-edit;
                    vertical-alignment: center;
                    text: "color theme";
                }

                ComboBox {
                    function to_string(color_scheme: ColorScheme) -> string {
                        return color_scheme == ColorScheme.dark ? "Dark" : "Light";
                    }
                    function to_theme(color_scheme_string: string) -> ColorScheme {
                        return color_scheme_string == to_string(ColorScheme.dark) ? ColorScheme.dark : ColorScheme.light;
                    }

                    model: [to_string(ColorScheme.dark), to_string(ColorScheme.light)];
                    current-index: to_theme(SlintReviewHelperSettings.color_scheme) == ColorScheme.dark ? 0 : 1;
                    current-value: SlintReviewHelperSettings.color_scheme;
                    selected(current-value) => {
                        SlintReviewHelperSettings.color_scheme = current-value;
                        Palette.color-scheme = to_theme(current-value);
                    }
                }
            }
        }

        HorizontalLayout {
            spacing: Style.size.spacing;
            alignment: end;

            Button {
                text: "Cancel";
                clicked => {
                    root.close()
                }
            }

            Button {
                text: "Save";
                clicked => {
                    SlintReviewHelperSettings.save();
                    root.close();
                }
            }
        }
    }
}
