import { Button, VerticalBox , HorizontalBox, LineEdit, ListView, CheckBox, GroupBox, Palette, TabWidget } from "std-widgets.slint";
import { Style } from "style.slint";
import { Notes, NoteItem, NotesView } from "notes_view.slint";
import { FileDiffView, Diff, DiffFileItem } from "file_diff_view.slint";
import { DiffConfigView, Repository} from "diff_config_view.slint";
import { Popup } from "popup.slint";
import { FileNotesPopup } from "file_notes_popup.slint";
import { StringUtils } from "string_utils.slint";
import { Menu, MenuItem } from "menu.slint";
import { AppConfig, AppConfigPopup } from "app_config_popup.slint";

import { OverallStatistics, OverallDiffStats } from "overall_statistics.slint";

import { CommitPickerAdapter } from "commit_picker.slint";

export { AppConfig, CommitPickerAdapter, Notes, NoteItem, Diff, DiffFileItem, Repository, StringUtils, OverallDiffStats }

export global Project {
    in property <bool> has_modifications: false;
    in property <string> path;
    out property <bool> is_loaded: path != "";
    callback open;
    callback new;
    callback save;
}

export component AppWindow inherits Window {
    callback close;

    width: 1000px;
    height: 1000px;
    title: Project.path;

    notes-popup := FileNotesPopup {
        initial_x: (root.width / 2) - (self.width / 2);
        initial_y: (root.height / 2) - (self.height / 2);
    }
    app-config-popup := AppConfigPopup {
        initial_x: (root.width / 2) - (self.width / 2);
        initial_y: (root.height / 2) - (self.height / 2);
    }

    VerticalLayout {
        menu-rect := Rectangle {
            background: #262525;
            height: 40px;

            HorizontalLayout {
                alignment: space-between;
                spacing: Style.spacing;

                HorizontalLayout {
                    spacing: Style.spacing;

                    Menu {
                        text: "File";

                        MenuItem {
                            text: "New";
                            clicked => { Project.new() }
                        }
                        MenuItem {
                            text: "Open";
                            clicked => { Project.open() }
                        }
                        MenuItem {
                            text: "Save";
                            enabled: Project.is_loaded && Project.has_modifications;
                            clicked => { Project.save() }
                        }
                        MenuItem {
                            text: "Close";
                            clicked => { root.close() }
                        }
                    }
                    Menu {
                        text: "Edit";

                        MenuItem {
                            text: "Config";
                            clicked => { app-config-popup.open() }
                        }
                    }
                }
                if Project.has_modifications: HorizontalBox {
                    Image {
                        source: @image-url("../assets/icons/save.svg");
                    }
                }
            }
        }
        TabWidget {
            Tab {
                title: "File Diff";

                VerticalBox {
                    if Project.is_loaded: DiffConfigView {
                        height: 100px;
                        vertical-stretch: 0;
                    }
                    if Repository.is_loaded: OverallStatistics {
                        vertical-stretch: 0;
                    }
                    if Repository.is_loaded: FileDiffView {
                        open-file-notes-popup(file) => { notes-popup.open-notes(file) }
                    }
                }
            }
            Tab {
                title: "Notes";

                NotesView {}
            }
        }

    }
}
