import {
    Button,
    VerticalBox,
    HorizontalBox,
    LineEdit,
    ListView,
    CheckBox,
    GroupBox,
    Palette,
    TabWidget,
} from "std-widgets.slint";

import { Style } from "style.slint";
import { NotesView } from "notes_view.slint";
import { FileDiffView } from "file_diff_view.slint";
import { Popup } from "popup.slint";
import { FileNotesPopup } from "file_notes_popup.slint";
import { Menu, MenuItem } from "menu.slint";
import { AppConfigPopup } from "app_settings_popup.slint";
import { DiffConfigView } from "diff_config_view.slint";
import { OverallStatistics } from "overall_statistics.slint";
import { TabView, TabViewItem } from "tabview.slint";
import { RepositorySettingsPopup } from "repository_settings_popup.slint";

import {
    Repository,
    CommitPickerAdapter,
    OverallDiffStats,
    SlintReviewHelperSettings,
    SlintStringUtils,
    Diff,
    DiffFileItem,
    Notes,
    NoteItem,
    FilePickerAdapter,
    SlintModelUtils,
    SlintRepository,
    SlintReviewHelper,
    SlintResult,
    SlintErrors,
    SlintErrorEntry,
    SlintDiffRange,
    SlintReviewIdParameters,
    SlintNoteIdParamters,
    SlintFileDiffIdParamters,
    SlintRepositoryCallbacks,
    SlintReviewCallbacks,
    SlintCommitPickerAdapter,
    SlintCommit,
    SlintCommitSortCriterion,
    SlintFilePickerAdapter,
} from "globals.slint";
import { SubSectionText } from "sub_section_text.slint";
import { ToolButton } from "tool_button.slint";
import { RepositoryTabViewItem } from "respository_tab_view_item.slint";
import { ErrorPopup } from "error_popup.slint";

export { 
    SlintReviewCallbacks,
    SlintRepositoryCallbacks,
    SlintReviewHelperSettings,
    FilePickerAdapter,
    CommitPickerAdapter,
    Notes,
    NoteItem,
    Diff,
    DiffFileItem,
    Repository,
    SlintStringUtils,
    OverallDiffStats,
    SlintModelUtils,
    SlintRepository,
    SlintReviewHelper,
    SlintResult,
    SlintErrors,
    SlintErrorEntry,
    SlintDiffRange,
    SlintReviewIdParameters,
    SlintNoteIdParamters,
    SlintFileDiffIdParamters,
    SlintCommitPickerAdapter,
    SlintCommit,
    SlintCommitSortCriterion,
    SlintFilePickerAdapter,
}

export component AppWindow inherits Window {
    private property <int> selected_repository_index <=> tab-view.current-index;
    in property <string> config_color_scheme;
    callback close;
    callback request_show_error(SlintResult);

    request_show_error(e) => {
        error-popup.show_error(e);
    }

    changed config_color_scheme => {
        Palette.color-scheme = config_color_scheme == "Dark" ? ColorScheme.dark : ColorScheme.light;
    }

    preferred-width: 1600px;
    preferred-height: 1200px;
    title: "review_helper";

    icon: @image-url("../assets/icons/review_helper.png");
    notes-popup := FileNotesPopup {
        initial_x: (root.width / 2) - (self.width / 2);
        initial_y: (root.height / 2) - (self.height / 2);
        enable_close_button: true;
    }

    app-config-popup := AppConfigPopup {
        initial_x: (root.width / 2) - (self.width / 2);
        initial_y: (root.height / 2) - (self.height / 2);
    }

    error-popup := ErrorPopup {
        initial_x: (root.width / 2) - (self.width / 2);
        initial_y: (root.height / 2) - (self.height / 2);
    }

    repository-settings-popup := RepositorySettingsPopup {
        initial_x: (root.width / 2) - (self.width / 2);
        initial_y: (root.height / 2) - (self.height / 2);
        base-branch-changed(base-branch) => {
            SlintReviewHelper.repositories[root.selected_repository_index].base-branch = base-branch;
            SlintRepositoryCallbacks.repository_changed(SlintReviewHelper.repositories[root.selected_repository_index].id, base-branch);
        }
    }

    VerticalLayout {
        menu-rect := Rectangle {
            height: 40px;

            HorizontalLayout {
                alignment: space-between;
                spacing: Style.size.spacing;

                HorizontalLayout {
                    spacing: Style.size.spacing;

                    Menu {
                        text: "File";
                        MenuItem {
                            text: "Close";
                            clicked => {
                                root.close()
                            }
                        }
                    }

                    Menu {
                        text: "Settings";

                        MenuItem {
                            text: "ReviewHelper";
                            clicked => {
                                app-config-popup.open()
                            }
                        }

                        MenuItem {
                            enabled: root.selected_repository_index != -1;
                            text: "Respository";
                            clicked => {
                                repository-settings-popup.show(SlintReviewHelper.repositories[root.selected_repository_index]);
                            }
                        }
                    }
                }
            }
        }

        tab-view := TabView {
            model: SlintReviewHelper.repository_names;
            request-create => { SlintReviewHelper.new_repository() }
            for repository[idx] in SlintReviewHelper.repositories: RepositoryTabViewItem {
                index: idx;
                current-index <=> parent.current-index;
                repository_id: repository.id;
                repository_name: repository.name;
                review_model: repository.review_model;
            }
        }
    }
}
