import { LineEdit, Button, VerticalBox, HorizontalBox, StandardTableView } from "std-widgets.slint";
import { CommitPicker } from "commit_picker.slint";
import { Style } from "style.slint";

export enum CommitPickerPosition { Left, Right }

export component CommitEditor inherits Rectangle {
    in property <CommitPickerPosition> picker-position;
    in property <string> placeholder-text: "";
    in-out property <string> commit: "";

    commit_picker := CommitPicker {
        accepted (commit) => { commit-edit.text = commit; }
    }
    picker-button := Button {
        width: Style.control_small_width;
        x: root.picker-position == CommitPickerPosition.Left ? 0px : commit-edit.width + Style.spacing;
        icon: @image-url("../assets/icons/tree.svg");
        clicked => {
            commit_picker.show();
        }
    }
    commit-edit := LineEdit {
        width: root.width - picker-button.width - Style.spacing;
        x: root.picker-position == CommitPickerPosition.Left ? picker-button.width + Style.spacing : 0px;
        placeholder-text: root.placeholder-text;
        text <=> root.commit;
    }
}