import { LineEdit, Button, VerticalBox, HorizontalBox, Palette, StandardTableView, ListView } from "std-widgets.slint";
import { Style } from "style.slint";
import { SlintCommitPickerAdapter } from "globals.slint";
import { ToolButton } from "tool_button.slint";

export component CommitPicker inherits PopupWindow {
    in property <int> repository_id;
    private property <bool> is_sort_ascending: true;
    private property <int> selected_index: -1;

    x: 20px;
    y: 20px;
    height: 600px;
    width: 840px;
    close-policy: close-on-click-outside;

    callback accepted(string);

    Rectangle {
        height: 100%;
        width: 100%;
        background: Palette.background;
        border-color: Palette.border;
        border-width: Style.size.border_width;
        border-radius: Style.size.menu_border_radius;

        VerticalBox {
            HorizontalLayout {
                spacing: Style.size.spacing;

                ToolButton {
                    source: @image-url("../assets/icons/location.svg");
                    text: "Merge-Branch";
                    clicked => {
                        root.selected_index = SlintCommitPickerAdapter.index_of_merge_base(root.repository_id);
                    }
                }
            }

            HorizontalLayout {
                spacing: Style.size.spacing;

                LineEdit {
                    placeholder-text: "text filter";
                    edited(text) => {
                        SlintCommitPickerAdapter.filter_commits(text)
                    }
                }

                ToolButton {
                    source: @image-url("../assets/icons/refresh.svg");
                    clicked => {
                        SlintCommitPickerAdapter.refresh(root.repository_id);
                    }
                }
            }

            HorizontalLayout {
                Text {
                    width: 80px;
                    text: "Commit";
                }
                Text {
                    width: 400px;
                    text: "Message";
                }
                Text {
                    width: 160px;
                    text: "Author";
                }
                Text {
                    text: "Date";
                }
            }
            ListView {
                for commit[index] in SlintCommitPickerAdapter.ui_commit_model(): HorizontalLayout {
                    me := Text {
                        width: 80px;
                        text: commit.commit_id;
                        overflow: elide;
                        states [
                            selected when root.selected_index == index: {
                                me.color: red;
                            }
                        ]
                    }
                    Text {
                        width: 400px;
                        text: commit.message;
                        overflow: elide;
                    }
                    Text {
                        width: 160px;
                        text: commit.author;
                        overflow: elide;
                    }
                    Text {
                        text: commit.date;
                        overflow: elide;
                    }
                }
            }

            HorizontalBox {
                alignment: end;
                Button {
                    height: Style.size.control_height;
                    text: "Cancel";
                    clicked => {
                        root.close()
                    }
                }

                Button {
                    height: Style.size.control_height;
                    text: "Apply";
                    clicked => {
                        // root.accepted(CommitPickerAdapter.commit_model[commit_table_view.current-row][0].text);
                        root.close();
                    }
                }
            }
        }
    }
}
