
import { GroupBox, LineEdit, Button } from "std-widgets.slint";
import { Diff } from "file_diff_view.slint";
import { Style } from "style.slint";

export global Repository {
    in property <string> path;
    out property <bool> is_loaded: path != "";
    callback open;
}

export component DiffConfigView inherits GroupBox {
    title: "Git Repo: ";

    VerticalLayout {
        spacing: Style.spacing;

        HorizontalLayout {
            spacing: Style.spacing;
            LineEdit {
                read-only: true;
                text: Repository.path;
            }
            Button {
                icon: @image-url("../assets/icons/folder_open.svg");
                clicked => { Repository.open() }
            }
        }
        HorizontalLayout {
            visible: Repository.path != "";
            spacing: Style.spacing;
            start-commit-edit := LineEdit {
                placeholder-text: "Start Commit SHA";
                text: Diff.start_commit;
            }
            Button {
                icon: @image-url("../assets/icons/compare.svg");
                clicked => {
                    Diff.diff-start-end(start-commit-edit.text, end-commit-edit.text);
                }
            }
            end-commit-edit := LineEdit {
                placeholder-text: "End Commit SHA";
                text: Diff.end_commit;
            }
        }
    }
}
