import { VerticalBox, LineEdit, ListView, CheckBox, Button } from "std-widgets.slint";

import { Popup } from "popup.slint";
import { Style } from "style.slint";
import { Notes, NoteItem, StringUtils } from "globals.slint";
import { FileNoteDelegate } from "file_note_delegate.slint";

export component FileNotesPopup inherits Popup {
    private property <string> file: "<empty>";
    private property <[NoteItem]> model;

    public function open-notes(file: string) {
        self.file = file;
        self.model = Notes.file-notes-model(file);
        self.open();
    }

    title: StringUtils.filename(self.file);

    VerticalBox {
        LineEdit {
            height: Style.size.control_height;
            placeholder-text: "Add comment here...";
            accepted => {
                Notes.add-note(self.text, root.file);
                self.text = "";
            }
        }

        ListView {
            for note_item in root.model: FileNoteDelegate {
                note: note-item;
            }
        }
    }
}
