import { LineEdit, CheckBox, Button } from "std-widgets.slint";

import { NoteItem, Notes } from "globals.slint";
import { Style } from "style.slint";
import { LineEdit } from "std-widgets.slint";
import { ToolButton } from "tool_button.slint";

export component FileNoteDelegate inherits HorizontalLayout {
    in property <NoteItem> note;

    spacing: Style.size.big_spacing;

    CheckBox {
        checked: note.is_fixed;
        toggled => {
            Notes.toggle-fixed(note.id)
        }
    }

    LineEdit {
        property <string> note_text: note.text;

        changed note_text => {
            self.text = note_text;
        }
        height: Style.size.control_height;
        text: note.text;
        accepted => {
            Notes.change-text(note.id, self.text)
        }
    }

    ToolButton {
        source: @image-url("../assets/icons/delete.svg");
        clicked => {
            Notes.delete-note(note.id)
        }
    }
}
