import {
    GroupBox,
    ListView,
    CheckBox,
    Button,
    Palette,
    LineEdit,
    VerticalBox,
    HorizontalBox,
    ComboBox,
} from "std-widgets.slint";

import { Style } from "style.slint";
import {
    SlintNote,
    SlintFileDiff,
    SlintFileDiffIdParamters,
    SlintReviewIdParameters,
    SlintReviewCallbacks,
    SlintFilterReviewState,
    SlintSortCriteria,
    SlintFileDiffIdParamters,
    SlintChangeTypeUtils,
    SlintFileDiffs,
} from "globals.slint";
import { FileNoteDelegate } from "file_note_delegate.slint";
import { ToolButton } from "controls/tool_button.slint";

export component FileDiffView inherits VerticalLayout {
    in property <SlintReviewIdParameters> review_id_parameters;
    in property <[SlintNote]> notes_model;
    private property <[SlintFileDiff]> file_diff_model: SlintReviewCallbacks.file_diff_ui_model(root.review_id_parameters);
    private property <int> selected_id: -1;
    private property <int> extended_file_id: -1;
    private property <int> model_count: root.file_diff_model.length;
    private property <bool> is_selected_id_in_model: true;
    changed selected_id => {
        if (selected_id != -1 && selected_id != extended_file_id) {
            extended_file_id = -1;
        }
    }
    changed model_count => {
        if (model_count > 0 && selected_id != -1) {
            is_selected_id_in_model = SlintReviewCallbacks.exists_file_diff({
                review_id_parameters: root.review_id_parameters,
                file_diff_id: root.selected_id,
            });
        }
    }
    changed is_selected_id_in_model => {
        if (!is_selected_id_in_model && selected_id != -1) {
            selected_id = -1;
        }
        if (!is_selected_id_in_model && extended_file_id != -1) {
            extended_file_id = -1;
        }
    }
    function select_id(id: int) {
        if (id != root.selected_id) {
            selected_id = id;
        }
    }
    spacing: Style.size.spacing;
    HorizontalLayout {
        spacing: Style.size.spacing;
        Image {
            source: @image-url("../assets/icons/filter_on.svg");
            colorize: Palette.foreground;
            width: Style.size.image_width;
        }

        LineEdit {
            horizontal-alignment: left;
            placeholder-text: @tr("Filter paths using wildcards");
            changed text => {
                SlintReviewCallbacks.set_file_diff_file_pattern(root.review_id_parameters, self.text);
            }
        }

        ComboBox {
            horizontal-stretch: 0;
            model: [@tr("Unfiltered"), @tr("Done"), @tr("Open")];
            selected(current-filter-review-state) => {
                if current-filter-review-state == @tr("Unfiltered") {
                    SlintReviewCallbacks.set_file_diff_review_state(root.review_id_parameters, SlintFilterReviewState.Unfiltered);
                }
                if current-filter-review-state == @tr("Done") {
                    SlintReviewCallbacks.set_file_diff_review_state(root.review_id_parameters, SlintFilterReviewState.Done);
                }
                if current-filter-review-state == @tr("Open") {
                    SlintReviewCallbacks.set_file_diff_review_state(root.review_id_parameters, SlintFilterReviewState.Open);
                }
            }
        }

        Image {
            source: @image-url("../assets/icons/sort.svg");
            colorize: Palette.foreground;
            width: Style.size.image_width;
        }

        ComboBox {
            horizontal-stretch: 0;
            model: [@tr("Name"), @tr("Extension"), @tr("IsDone")];
            selected(current-criteria) => {
                if current-criteria == @tr("Name") {
                    SlintReviewCallbacks.set_file_diff_sort-criteria(root.review_id_parameters, SlintSortCriteria.Name);
                }
                if current-criteria == @tr("IsDone") {
                    SlintReviewCallbacks.set_file_diff_sort-criteria(root.review_id_parameters, SlintSortCriteria.IsDone);
                }
                if current-criteria == @tr("Extension") {
                    SlintReviewCallbacks.set_file_diff_sort-criteria(root.review_id_parameters, SlintSortCriteria.Extension);
                }
            }
        }
    }

    ListView {
        horizontal-scrollbar-policy: always-off;
        vertical-scrollbar-policy: always-off;
        for data[idx] in root.file_diff_model: Rectangle {
            private property <bool> is_selected: root.selected_id == data.id;
            private property <SlintFileDiffIdParamters> file_diff_id_parameter: {
                review_id_parameters: root.review_id_parameters,
                file_diff_id: data.id,
            };
            states [
                selected when selected_id == data.id: {
                    background: Palette.control-background.brighter(0.2);
                    border-width: Style.size.border_width;
                    border-radius: Style.size.border_radius;
                }
            ]
            TouchArea {
                clicked => {
                    root.select_id(data.id)
                }
                double-clicked => {
                    SlintReviewCallbacks.show_file_differences(file_diff_id_parameter);
                }
                VerticalLayout {
                    padding-left: Style.size.spacing;
                    padding-right: Style.size.spacing / 2;
                    spacing: Style.size.spacing;
                    HorizontalLayout {
                        height: Style.size.delegate_height;
                        alignment: space-between;
                        spacing: 2px;

                        HorizontalLayout {
                            spacing: Style.size.spacing;

                            VerticalLayout {
                                alignment: center;
                                Rectangle {
                                    background: Palette.control-background;
                                    border-radius: Style.size.border_radius;
                                    border-width: Style.size.border_width;
                                    border-color: Palette.border;
                                    width: Style.size.image_width + 4px;
                                    height: Style.size.image_width + 4px;
                                    states [
                                        is_pressed when is_selected && ta.pressed: {
                                            background: Palette.alternate-background;
                                        }
                                    ]
                                    Image {
                                        vertical-alignment: center;
                                        horizontal-alignment: center;
                                        width: Style.size.image_width;
                                        states [
                                            is_reviewed when data.is_reviewed: {
                                                source: @image-url("../assets/icons/checked.svg");
                                            }
                                        ]
                                        colorize: is_selected ? Palette.foreground : Style.palette.disabled;
                                    }

                                    ta := TouchArea {
                                        clicked => {
                                            if !is_selected {
                                                root.select_id(data.id);
                                            } else {
                                                SlintReviewCallbacks.change_file_diff_is_reviewed(file_diff_id_parameter, !data.is_reviewed);
                                            }
                                        }
                                    }
                                }
                            }

                            Text {
                                overflow: elide;
                                font-size: 14px;
                                text: data.file-path;
                                vertical-alignment: center;
                                horizontal-alignment: left;
                            }
                        }

                        HorizontalLayout {
                            Image {
                                source: SlintChangeTypeUtils.to_icon(data.change_type);
                                horizontal-alignment: center;
                                colorize: Palette.foreground;
                            }

                            HorizontalLayout {
                                padding-top: Style.size.spacing / 2;
                                padding-bottom: Style.size.spacing / 2;
                                spacing: Style.size.spacing;
                                Rectangle {
                                    background: Style.palette.lines-added;
                                    border-radius: 5px;
                                    width: 40px;
                                    visible: data.added-lines != 0;
                                    Text {
                                        font-size: 14px;
                                        vertical-alignment: center;
                                        text: "\{data.added-lines != -1 ? data.added-lines : "??"}";
                                    }
                                }

                                Rectangle {
                                    background: Style.palette.lines-removed;
                                    border-radius: 5px;
                                    width: 40px;
                                    visible: data.removed-lines != 0;
                                    Text {
                                        font-size: 14px;
                                        vertical-alignment: center;
                                        text: "\{data.removed-lines != -1 ? data.removed-lines : "??"}";
                                    }
                                }

                                ToolButton {
                                    source: @image-url("../assets/icons/open_editor.svg");
                                    enabled: is_selected;
                                    clicked => {
                                        SlintFileDiffs.open_file_by_editor(root.review_id_parameters.repository-id, data.file-path);
                                    }
                                }

                                ToolButton {
                                    source: data.referenced_notes.length > 0 ? @image-url("../assets/icons/notes.svg") : @image-url("../assets/icons/note-add.svg");
                                    enabled: is_selected;
                                    checked: root.extended_file_id == data.id;
                                    clicked => {
                                        root.extended_file_id = root.extended_file_id == data.id ? -1 : data.id;
                                    }
                                }
                            }
                        }
                    }

                    if root.extended_file_id == data.id: VerticalBox {
                        LineEdit {
                            height: Style.size.control_height;
                            placeholder-text: @tr("Add comment here...");
                            accepted(new_text) => {
                                SlintReviewCallbacks.add_note(root.review_id_parameters, new_text, data.file_path);
                                self.text = "";
                            }
                        }

                        for note_index in data.referenced_notes: FileNoteDelegate {
                            review_id_parameters: root.review_id_parameters;
                            note: root.notes_model[note_index];
                        }
                    }
                }
            }
        }
    }
}
