import { VerticalBox, LineEdit, ListView, CheckBox, Button } from "std-widgets.slint";

import { Popup } from "popup.slint";
import { Style } from "style.slint";
import { Notes, NoteItem, StringUtils } from "globals.slint";

export component FileNotesPopup inherits Popup {
    private property <string> file: "<empty>";
    private property <[NoteItem]> model;

    public function open-notes(file: string) {
        self.file = file;
        self.model = Notes.file-notes-model(file);
        self.open();
    }

    title: StringUtils.filename(self.file);

    VerticalBox {
        LineEdit {
            height: Style.control_height;
            placeholder-text: "Add comment here...";
            accepted => {
                Notes.add-note(self.text, root.file);
                self.text = "";
            }
        }

        ListView {
            for note[idx] in root.model: HorizontalLayout {
                spacing: Style.big_spacing;

                CheckBox {
                    checked: note.is_fixed;
                    toggled => {
                        Notes.toggle-fixed(note.id)
                    }
                }

                LineEdit {
                    property <string> note_text: note.text;

                    changed note_text => {
                        self.text = note_text;
                    }
                    height: Style.control_height;
                    text: note.text;
                    accepted => {
                        Notes.change-text(note.id, self.text)
                    }
                }

                Button {
                    icon: @image-url("../assets/icons/delete.svg");
                    clicked => {
                        Notes.delete-note(note.id)
                    }
                }
            }
        }
    }
}
