export global SlintReviewHelperSettings {
    in-out property <string> diff_tool;
    in-out property <[string]> diff_tool_model;
    in-out property <string> editor;
    in-out property <string> editor_args;
    in-out property <string> color_scheme;

    callback save();
    callback refresh_diff_tool_model();
}

export enum SlintResult {
    Ok,
    GitCommandFailed,
    RepositoryExists,
    NoGitDirectory,
    StoreFailed,
    ModelItemNotExists,
    LoadReviewNamesFailed,
    QueryingDiffToolsFailed,
    ReviewAlreadyLoaded,
    LoadReviewFailed,
    ReviewAlreadyExists,
    FindFileDifferenceFailed,
    ShowFileDifferencesFailed,
    DeleteReviewFailed,
    DeleteRepositoryFailed,
}

export enum SlintChangeType {
    Invalid,
    Added,
    Copied,
    Deleted,
    Modified,
    Renamed,
    TypChanged,
    Unmerged,
    Unknown,
    Broken
}

export global SlintChangeTypeUtils {
    public pure function to_icon(change_type: SlintChangeType) -> image {
        if (change_type == SlintChangeType.Added) {
            return @image-url("../assets/icons/git_file_added.svg");
        } else if (change_type == SlintChangeType.Broken) {
            return @image-url("../assets/icons/git_file_broken.svg");
        } else if (change_type == SlintChangeType.Copied) {
            return @image-url("../assets/icons/git_file_copied.svg");
        } else if (change_type == SlintChangeType.Deleted) {
            return @image-url("../assets/icons/git_file_deleted.svg");
        } else if (change_type == SlintChangeType.Modified) {
            return @image-url("../assets/icons/git_file_edited.svg");
        } else if (change_type == SlintChangeType.Renamed) {
            return @image-url("../assets/icons/git_file_renamed.svg");
        } else if (change_type == SlintChangeType.TypChanged) {
            return @image-url("../assets/icons/git_file_type_changed.svg");
        } else if (change_type == SlintChangeType.Unknown) {
            return @image-url("../assets/icons/git_file_unknown.svg");
        } else if (change_type == SlintChangeType.Unmerged) {
            return @image-url("../assets/icons/git_file_unmerged.svg");
        }
        return @image-url("../assets/icons/invalid.svg");
    }
}

export struct SlintFileDiff {
    id: int,
    added_lines: int,
    removed_lines: int,
    file_path: string,
    is_reviewed: bool,
    change_type: SlintChangeType,    
}

export struct SlintNote {
    id: int,
    text: string,
    is_fixed: bool,
    context: string,
}

export struct SlintReview {
    id: int,
    name: string,
    start_diff: string,
    end_diff: string,
    note_model: [SlintNote],
    file_diff_model: [SlintFileDiff],
    is_loaded: bool,
}

export struct SlintRepository {
    id: int,
    name: string,
    path: string,
    first_commit: string,
    base_branch: string,
    review_model: [SlintReview],
    // commit_model: [[StandardListViewItem]],
}

export struct SlintErrorEntry {
    error_type: SlintResult,
    text: string,
}

export global SlintErrors {
    in property <[SlintErrorEntry]> model;
}

export struct SlintDiffRange {
    start: string,
    end: string,
}

export struct SlintReviewIdParameters {
    repository_id: int,
    review_id: int,
}

export struct SlintNoteIdParamters {
    review_id_parameters: SlintReviewIdParameters,
    note_id: int,
}

export struct SlintFileDiffIdParamters {
    review_id_parameters: SlintReviewIdParameters,
    file_diff_id: int,
}

export global SlintReviewCallbacks {
    callback load_review(SlintReviewIdParameters);
    pure callback review_id_to_index(int, [SlintReview]) -> int;
    callback find_file_changes(SlintReviewIdParameters, SlintDiffRange);
    callback change_note_text(SlintNoteIdParamters, string);
    callback change_note_context(SlintNoteIdParamters, string);
    callback change_note_is_done(SlintNoteIdParamters, bool);
    callback delete_note(SlintNoteIdParamters);
    callback add_note(SlintReviewIdParameters, string, string);
    callback change_file_diff_is_reviewed(SlintFileDiffIdParamters, bool);
    callback show_file_differences(SlintFileDiffIdParamters);
}

export global SlintRepositoryCallbacks {
    callback delete_review(SlintReviewIdParameters);
    callback new_review(int, string);
    callback load_repository(int);
    callback repository_changed(int, string);
}

export global SlintReviewHelper {
    in property <[SlintRepository]> repositories;
    in property <[string]> repository_names;
    callback new_repository();
    callback delete_repository(int);
}

export global Repository {
    in property <string> path;
    out property <bool> is_loaded: path != "";
    callback open;
}

export enum ChangeType {
    Invalid,
    Added,
    Copied,
    Deleted,
    Modified,
    Renamed,
    TypChanged,
    Unmerged,
    Unknown,
    Broken
}

export global ChangeTypeUtils {
    public pure function to_icon(change_type: ChangeType) -> image {
        if (change_type == ChangeType.Added) {
            return @image-url("../assets/icons/git_file_added.svg");
        } else if (change_type == ChangeType.Broken) {
            return @image-url("../assets/icons/git_file_broken.svg");
        } else if (change_type == ChangeType.Copied) {
            return @image-url("../assets/icons/git_file_copied.svg");
        } else if (change_type == ChangeType.Deleted) {
            return @image-url("../assets/icons/git_file_deleted.svg");
        } else if (change_type == ChangeType.Modified) {
            return @image-url("../assets/icons/git_file_edited.svg");
        } else if (change_type == ChangeType.Renamed) {
            return @image-url("../assets/icons/git_file_renamed.svg");
        } else if (change_type == ChangeType.TypChanged) {
            return @image-url("../assets/icons/git_file_type_changed.svg");
        } else if (change_type == ChangeType.Unknown) {
            return @image-url("../assets/icons/git_file_unknown.svg");
        } else if (change_type == ChangeType.Unmerged) {
            return @image-url("../assets/icons/git_file_unmerged.svg");
        }
        return @image-url("../assets/icons/invalid.svg");
    }
}

export enum SortCriteria {
    Name,
    Extension,
    IsDone
}

export struct DiffFileItem {
    id: int,
    added_lines: int,
    removed_lines: int,
    text: string,
    is_reviewed: bool,
    change_type: ChangeType,
}

export enum FilterReviewState {
    Unfiltered,
    Done,
    Open
}

export global Diff {
    in property <string> start_commit;
    in property <string> end_commit;
    in property <[DiffFileItem]> diff_model;
    in property <SortCriteria> current_sort_criteria: SortCriteria.Name;
    in property <FilterReviewState> current_filter_review_state: FilterReviewState.Unfiltered;
    callback diff-start-end(string, string);
    callback open-file-diff(int);
    callback open-file(string);
    callback toggle-is-reviewed(int);
    callback set-sort-criteria(SortCriteria);
    callback filter-file-diff(string);
    callback set-filter-review-state(FilterReviewState);
    callback diff-model-contains-id(int) -> bool;
}

export struct OverallStat {
    change_type: ChangeType,
    count: int,
}

export global OverallDiffStats {
    in property <int> added_lines: 0;
    in property <int> removed_lines: 0;
    in property <[OverallStat]> model;
}

export global CommitPickerAdapter {
    in property <[[StandardListViewItem]]> commit_model;

    callback filter_commits(string);
    callback sort_commits(int, bool);
    callback refresh();
    callback index_of_merge_base(string) -> int;
}

export struct NoteItem  {
    id: int,
    text: string,
    is_fixed: bool,
    context: string,
}

export enum SortOrder {
    Ascending,
    Descending
}

export enum NoteSortCriteria {
    NoteText,
    Context
}

export global Notes {
    in property <[NoteItem]> notes_model;
    in property <SortOrder> sort_order;
    in property <NoteSortCriteria> sort_criteria;
    callback add-note(string, string);
    callback change-text(int, string);
    callback change-context(int, string);
    callback toggle-fixed(int);
    callback delete-note(int);
    pure callback file-notes-model(string) -> [NoteItem];
    callback set-notes-text-filter(string);
    callback set-notes-context-filter(string);
    callback set-notes-sorting(NoteSortCriteria, SortOrder);
}

export global SlintStringUtils {
    pure callback filename(string) -> string;
    pure callback is_valid_name(string) -> bool;
}

export global SlintModelUtils {
    pure callback index_of_string([string], string) -> int;
}

export global FilePickerAdapter {
    in property <[string]> files_model;
    callback set-filter(string);
    pure callback contains-model-context(string) -> bool;
}
