import { Style } from "style.slint";
import { Palette } from "std-widgets.slint";

export component ImageButton inherits Rectangle {
    out property <bool> pressed: ta.pressed;
    in-out property <bool> enabled <=> ta.enabled;
    in property <image> source;
    callback clicked();
    width: image.width + 2 * Style.big_spacing;
    background: ta.pressed ? Palette.alternate-background : Palette.control-background;
    border-radius: Style.border_radius;
    border-width: Style.border_width;
    image := Image {
        vertical-alignment: center;
        horizontal-alignment: center;
        width: Style.image_width;
        source: root.source;
        colorize: root.enabled ? Palette.foreground : Style.palette.disabled;
    }

    ta := TouchArea {
        clicked => {
            root.clicked()
        }
    }
}
