import { Palette } from "std-widgets.slint";
import { Style } from "style.slint";

export component Menu inherits Rectangle {
    in property <string> text <=> button-text.text;
    in-out property <bool> enabled: true;

    popup := PopupWindow {
        y: root.height;

        Rectangle {
            background: Palette.background;
            border-color: Palette.border;
            border-width: Style.size.border_width;
            border-radius: Style.size.menu_border_radius;

            layout := VerticalLayout {
                padding: 5px;
                @children
            }
        }
    }

    background: click-area.has-hover ? Style.palette.selected : Palette.background;
    min-width: button-text.width + 15px;

    button-text := Text {
        vertical-alignment: center;
        horizontal-alignment: left;
        font-size: Style.font.menu-size;
        color: root.enabled ? Palette.control-foreground : Style.palette.disabled;
    }

    click-area := TouchArea {
        enabled: root.enabled;
        clicked => {
            popup.show()
        }
    }
}

export component MenuItem inherits Rectangle {
    callback clicked;

    in property <string> text <=> button-text.text;
    in-out property <bool> enabled: true;

    background: click-area.has-hover ? Style.palette.selected : Palette.background;
    border-radius: Style.size.menu_border_radius;
    min-height: 40px;

    HorizontalLayout {
        padding: 10px;
        alignment: start;
        button-text := Text {
            vertical-alignment: center;
            horizontal-alignment: left;
            font-size: Style.font.menu-size;
            color: root.enabled ? Palette.control-foreground : Style.palette.disabled;
        }
    }

    click-area := TouchArea {
        enabled: root.enabled;
        clicked => {
            root.clicked()
        }
    }
}
