import { GroupBox, LineEdit, Button, ListView, CheckBox } from "std-widgets.slint";
import { Style } from "style.slint";

export struct NoteItem  {
    text: string,
    is_fixed: bool,
}

export global Notes {
    in property <[NoteItem]> notes_model;
    callback add-note(string);
    callback change-text(int, string);
    callback toggle-fixed(int);
}

export component NotesView inherits GroupBox {
    title: "Notes:";

    VerticalLayout {
        alignment: start;
        spacing: Style.spacing;

        LineEdit {
            vertical-stretch: 0;
            placeholder-text: "Add comment here...";
            accepted => {
                if (self.text != "") {
                    Notes.add-note(self.text);
                    self.text = "";
                }
            }
        }
        ListView {
            height: Math.min(200px, Notes.notes_model.length * 50px);
            padding-right: 0;
            padding-left: 0;
            for data[idx] in Notes.notes_model: HorizontalLayout {
                spacing: 2px;
                padding-top: Style.spacing;

                CheckBox {
                    checked: data.is_fixed;
                    toggled => {
                        Notes.toggle-fixed(idx);
                    }
                }
                LineEdit {
                    horizontal-stretch: 1;
                    text: data.text;
                    accepted => {
                        Notes.change-text(idx, self.text);
                    }
                }
            }
        }
    }
}
