import { GroupBox, HorizontalBox, Palette } from "std-widgets.slint";

import { Style } from "style.slint";
import { ChangeTypeUtils, ChangeType, OverallDiffStats } from "globals.slint";

export component OverallStatistics inherits HorizontalLayout {
    alignment: start;
    for data in OverallDiffStats.model: VerticalLayout {
        Image {
            source: ChangeTypeUtils.to_icon(data.change_type);
            height: Style.size.control_height;
            colorize: Palette.foreground;
        }

        Text {
            text: "\{data.count}";
            horizontal-alignment: center;
        }
    }
    VerticalLayout {
        Image {
            source: @image-url("../assets/icons/add.svg");
            colorize: Style.palette.lines-added;
            height: Style.size.control_height;
        }

        Text {
            text: OverallDiffStats.added_lines > 0 ? "\{OverallDiffStats.added_lines}" : "??";
            horizontal-alignment: center;
        }
    }

    VerticalLayout {
        Image {
            source: @image-url("../assets/icons/remove.svg");
            colorize: Style.palette.lines-removed;
            height: Style.size.control_height;
        }

        Text {
            text: OverallDiffStats.removed_lines > 0 ? "\{OverallDiffStats.removed_lines}" : "??";
            horizontal-alignment: center;
        }
    }
}
