import { Button, VerticalBox, LineEdit, ListView, CheckBox, Palette } from "std-widgets.slint";

import { ToolButton } from "tool_button.slint";
import { Style } from "style.slint";

export component Popup inherits Rectangle {
    in property <length> initial_x;
    in property <length> initial_y;
    in property <string> title;
    in property <bool> enable_close_button: false;
    callback closed();

    public function open() {
        self.visible = true;
    }
    public function close() {
        self.visible = false;
    }

    width: layout.preferred-width;
    height: layout.preferred-height;
    background: Palette.background;
    border-color: Palette.border;
    border-width: Style.size.border_width;
    border-radius: Style.size.menu_border_radius;
    x: self.initial_x;
    y: self.initial_y;
    z: 1000;
    visible: false;

    changed visible => {
        if (root.visible == false) {
            root.closed();
        }
    }

    layout := VerticalLayout {
        horizontal-stretch: 0;
        vertical-stretch: 0;
        padding-top: 1px;
        padding-left: 1px;
        padding-right: 1px;
        spacing: Style.size.spacing;
        Rectangle {
            height: Style.size.control_height;
            border-top-left-radius: 10px;
            border-top-right-radius: 10px;

            HorizontalLayout {
                title-text := Text {
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    text: root.title;
                }

                if root.enable_close_button: ToolButton {
                    height: Style.size.control_height;
                    width: 45px;
                    source: @image-url("../assets/icons/close.svg");
                    clicked => {
                        root.close()
                    }
                }
            }

            popup-ta := TouchArea {
                private property <length> start_x: 0;
                private property <length> start_y: 0;

                width: title-text.width;
                x: parent.x;
                y: parent.y;

                pointer-event(pe) => {
                    if (pe.button == PointerEventButton.left && pe.kind == PointerEventKind.down) {
                        start_x = popup-ta.mouse-x;
                        start_y = popup-ta.mouse-y;
                    }
                }
//                moved => {
//                    root.x += popup-ta.mouse-x - self.start_x;
//                    root.y += popup-ta.mouse-y - self.start_y;
//                }
            }
        }

        @children
    }
}
