import {
    VerticalBox,
    TabWidget,
    ListView,
    Palette,
    LineEdit, CheckBox, Button, HorizontalBox,
} from "std-widgets.slint";
import { ToolButton } from "tool_button.slint";
import { Style } from "style.slint";
import {
    SlintChangeTypeUtils,
    SlintDiffRange,
    SlintReviewHelper,
    SlintRepositoryCallbacks,
    SlintReview,
    SlintReviewCallbacks, SlintStringUtils,
    SlintReviewIdParameters,
    SlintFileDiffIdParamters,
    SlintNoteIdParamters,
} from "globals.slint";
import { TabButton, TabCreateButton, TabViewItem } from "tabview.slint";

export component RepositoryTabViewItem inherits TabViewItem {
    in property <int> repository_id;
    in property <string> repository_name;
    in property <[SlintReview]> review_model;
    private property <bool> is_repository_loaded: false;
    private property <int> selected_review_id: -1;
    private property <SlintReviewIdParameters> review_id_parameters: {
        repository_id: root.repository_id,
        review_id: root.selected_review_id,
    };

    changed is_active => {
        if (root.is_active && !root.is_repository_loaded) {
            SlintRepositoryCallbacks.load_repository(root.repository_id);
            root.is_repository_loaded = true;
        }
    }
    HorizontalLayout {
        Rectangle {
            width: 15%;
            VerticalLayout {
                padding-left: 5px;
                padding-right: 5px;
                spacing: Style.size.spacing;
                Text {
                    height: Style.size.control-height;
                    vertical-alignment: center;
                    horizontal-alignment: center;
                    text: "Reviews";
                }

                private property <bool> enable-new-review: false;
                TabCreateButton {
                    height: Style.size.control-height;
                    clicked => {
                        enable-new-review = true;
                    }
                }
                if enable-new-review: HorizontalLayout {
                    name-edit := LineEdit {
                        changed has-focus => {
                            if (!self.has-focus) {
                                enable-new-review = false;
                            }
                        }
                        input-type: text;
                        accepted(text) => {
                            if (SlintStringUtils.is_valid_name(text)) {
                                SlintRepositoryCallbacks.new_review(root.repository_id, text);
                                enable-new-review = false;
                            }
                        }
                        key-pressed(event) => {
                            if (event.text == Key.Escape) {
                                enable-new-review = false;
                                return EventResult.accept;
                            }
                            EventResult.reject
                        }
    
                    }
                    Image {
                        source: SlintStringUtils.is_valid_name(name-edit.text) ? @image-url("../assets/icons/success.svg") : @image-url("../assets/icons/failed.svg");
                        width: Style.size.image_width;
                    }       
                }
                

                ListView {
                    visible: root.review_model.length > 0; // NOTE workaround to get ListView visible with their elements
                    for review[idx] in root.review_model: HorizontalBox {
                        // height: Style.size.control-height + Style.size.spacing;
                        TabButton {
                            tab-text: review.name;
                            height: Style.size.control-height;
                            is-selected: root.selected_review_id == review.id;
                            clicked => {
                                root.selected_review_id = review.id;
                                if (!review.is_loaded) {
                                    SlintReviewCallbacks.load_review(root.review_id_parameters);
                                }
                            }
                        }
                        Button {
                            width: Style.size.control-small-width;
                            text: "del";
                            clicked => {
                                SlintRepositoryCallbacks.delete_review(root.review_id_parameters);
                            }
                        }
                    }
                }
            }
        }

        Rectangle {
            width: 1px;
            height: 100%;
            background: Palette.border;
        }

        Rectangle {
            private property <int> review_index: SlintReviewCallbacks.review_id_to_index(root.selected_review_id, root.review_model);
            width: 85%;

            if review_index != -1: VerticalLayout {
                HorizontalLayout {
                    spacing: Style.size.spacing;
                    TabWidget {
                        Tab {
                            title: "FileDiff";
                            Rectangle {
                                VerticalLayout {
                                    // alignment: start;
                                    spacing: Style.size.spacing;
                                    HorizontalLayout {
                                        spacing: Style.size.spacing;

                                        private property <SlintDiffRange> diff_range: {
                                            start: start-range-edit.text,
                                            end: end-range-edit.text,
                                        };

                                        start-range-edit := LineEdit {
                                            private property <string> commit: root.review_model[review_index].start_diff;
                                            changed commit => {
                                                self.text = commit;
                                            }
                                            text: root.review_model[review_index].start_diff;
                                            placeholder-text: "start";
                                        }

                                        ToolButton {
                                            text: "<=>";
                                            clicked => {
                                                SlintReviewCallbacks.find_file_changes(root.review_id_parameters, diff_range);
                                            }
                                        }

                                        end-range-edit := LineEdit {
                                            private property <string> commit: root.review_model[review_index].end_diff;
                                            changed commit => {
                                                self.text = commit;
                                            }

                                            text: root.review_model[review_index].end_diff;
                                            placeholder-text: "end";
                                        }
                                    }
                                    ListView {
                                        for file_diff in root.review_model[review_index].file_diff_model: HorizontalLayout {
                                            private property <SlintFileDiffIdParamters> id_parameters: {
                                                review_id_parameters: root.review_id_parameters,
                                                file_diff_id: file-diff.id,
                                            };

                                            CheckBox {
                                                private property <bool> is_reviewed: file_diff.is-reviewed;
                                                changed is_reviewed => {
                                                    self.checked = is_reviewed;
                                                }
                                                checked: is_reviewed;
                                                toggled => {
                                                    SlintReviewCallbacks.change_file_diff_is_reviewed(id_parameters, self.checked);
                                                }
                                            }
                                            Text {
                                                text: file-diff.file_path;
                                            }
                                            Text {
                                                text: file-diff.added_lines;
                                            }
                                            Text {
                                                text: file-diff.removed_lines;
                                            }
                                            Image {
                                                source: SlintChangeTypeUtils.to_icon(file-diff.change_type);
                                                colorize: Palette.foreground;
                                                width: Style.size.image_width;
                                            }
                                            Button {
                                                text: "open";
                                                clicked => {
                                                    SlintReviewCallbacks.show_file_differences(id_parameters);
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }

                        Tab {
                            title: "Notes";
                            Rectangle {
                                VerticalLayout {
                                    spacing: Style.size.spacing;
                                    HorizontalLayout {
                                        note-text-edit := LineEdit {
                                            placeholder-text: "note-text";
                                        }
                                        note-context-edit := LineEdit {
                                            placeholder-text: "note-context";
                                        }
                                        Button {
                                            text: "add";
                                            clicked => {
                                                SlintReviewCallbacks.add_note(root.review_id_parameters, note-text-edit.text, note-context-edit.text);
                                                note-context-edit.text = "";
                                                note-text-edit.text = "";
                                            }
                                        }
                                    }
                                    ListView {
                                        for note in root.review_model[review_index].note_model: HorizontalLayout {
                                            private property <SlintNoteIdParamters> id_parameters: {
                                                review_id_parameters: root.review_id_parameters,
                                                note_id: note.id,
                                            };
                                            height: Style.size.control-height;
                                            
                                            CheckBox {
                                                private property <bool> is_fixed: note.is-fixed;
                                                changed is_fixed => {
                                                    self.checked = is_fixed;
                                                }
                                                checked: is_fixed;
                                                toggled => {
                                                    SlintReviewCallbacks.change_note_is_done(id_parameters, self.checked);
                                                }
                                            }
                                            LineEdit {
                                                private property <string> note_text: note.text;
                                                changed note_text => {
                                                    self.text = note_text;
                                                }
                                                text: note.text;
                                                accepted(text) => {
                                                    SlintReviewCallbacks.change_note_text(id_parameters, text);
                                                }
                                            }
                                            LineEdit {
                                                private property <string> note_context: note.context;
                                                changed note_context => {
                                                    self.text = note_context;
                                                }
                                                text: note.context;
                                                accepted(text) => {
                                                    SlintReviewCallbacks.change_note_context(id_parameters, text);
                                                }
                                            }
                                            Button {
                                                text: "del";
                                                clicked => {
                                                    SlintReviewCallbacks.delete_note(id_parameters);
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
