import { VerticalBox, TabWidget, ListView } from "std-widgets.slint";
import { ToolButton } from "tool_button.slint";
import { Style } from "style.slint";
import { SlintRepository } from "globals.slint";
import { TabButton, TabCreateButton } from "tabview.slint";

export component RepositoryView inherits HorizontalLayout {
    in property <SlintRepository> repository;

    VerticalLayout {
        width: 15%;
        padding-left: 5px;
        padding-right: 5px;
        spacing: Style.size.spacing;

        Text {
            height: Style.size.control-height;
            vertical-alignment: center;
            horizontal-alignment: center;
            text: "Reviews";
        }

        TabCreateButton {
            height: Style.size.control-height;
        }

        ListView {
            for review in ["Rotation", "RayAlignment", "NewCoreModel"]: TabButton {
                tab-text: review;
                height: Style.size.control-height;
            }
        }
    }

    VerticalLayout {
        width: 85%;
        HorizontalLayout {
            spacing: Style.size.spacing;
            TabWidget {
                Tab {
                    title: "FileDiff";
                    Rectangle {
                        background: orange;
                    }
                }

                Tab {
                    title: "Notes";
                    Rectangle {
                        background: pink;
                    }
                }
            }
        }
    }
}
