import { Style } from "style.slint";
import { ToolButton } from "controls/tool_button.slint";
import { CommitEditor, CommitPickerPosition } from "commit_editor.slint";
import {
    SlintReview,
    SlintReviewIdParameters,
    SlintReviewCallbacks,
    SlintDiffRange,
} from "globals.slint";
import { CenterTabView, TabViewItem } from "controls/tabview.slint";
import { OverallStatistics } from "overall_statistics.slint";
import { Palette, Switch } from "std-widgets.slint";
import { FileDiffSetupView } from "file_diff_setup_view.slint";


export component ReviewView inherits Rectangle {
    in property <SlintReviewIdParameters> review_id_parameters;
    in property <[SlintReview]> review_model;
    private property <int> review_index: SlintReviewCallbacks.review_id_to_index(root.review_id_parameters.review_id, root.review_model);
    if root.review_index != -1: CenterTabView {
        image_model: [
            @image-url("../assets/icons/differences.svg"),
            @image-url("../assets/icons/notes.svg"),
        ];
        spacing: Style.size.big-spacing;
        TabViewItem {
            index: 0;
            current-index <=> parent.current-index;
            VerticalLayout {
                alignment: start;
                padding-top: Style.size.spacing;
                spacing: Style.size.big-spacing;
                FileDiffSetupView {
                    review_id_parameters: root.review_id_parameters;
                    start_diff: root.review_model[root.review_index].start_diff;
                    end_diff: root.review_model[root.review_index].end_diff;
                }

                OverallStatistics {
                    difference_statistics: root.review_model[root.review_index].difference_statistics;
                }
            }
        }

        TabViewItem {
            index: 1;
            current-index <=> parent.current-index;
        }
    }
}
