import { Style } from "style.slint";
import { ToolButton } from "controls/tool_button.slint";
import { CommitEditor, CommitPickerPosition } from "commit_editor.slint";
import {
    SlintReview,
    SlintReviewIdParameters,
    SlintReviewCallbacks,
    SlintDiffRange,
    SlintFileDiffIdParamters,
    SlintChangeTypeUtils,
    SlintNoteIdParamters,
    SlintContextType,
} from "globals.slint";
import { CenterTabView, TabViewItem } from "controls/tabview.slint";
import { OverallStatistics } from "overall_statistics.slint";
import {
    Palette,
    Switch,
    ListView,
    CheckBox,
    Button,
    LineEdit,
} from "std-widgets.slint";
import { FileDiffSetupView } from "file_diff_setup_view.slint";
import { FileDiffView } from "file_diff_view.slint";


export component ReviewView inherits Rectangle {
    in property <SlintReviewIdParameters> review_id_parameters;
    in property <[SlintReview]> review_model;
    private property <int> review_index: SlintReviewCallbacks.review_id_to_index(root.review_id_parameters.review_id, root.review_model);
    if root.review_index != -1: CenterTabView {
        image_model: [
            @image-url("../assets/icons/differences.svg"),
            @image-url("../assets/icons/notes.svg"),
        ];
        spacing: Style.size.big-spacing;
        TabViewItem {
            index: 0;
            current-index <=> parent.current-index;
            VerticalLayout {
                padding-top: Style.size.spacing;
                spacing: Style.size.big-spacing;
                FileDiffSetupView {
                    review_id_parameters: root.review_id_parameters;
                    start_diff: root.review_model[root.review_index].start_diff;
                    end_diff: root.review_model[root.review_index].end_diff;
                }

                OverallStatistics {
                    review_progress: root.review_model[root.review_index].review_progress;
                    note_progress: root.review_model[root.review_index].note_progress;
                    difference_statistics: root.review_model[root.review_index].difference_statistics;
                }

                FileDiffView {
                    review_id_parameters: root.review_id_parameters;
                    notes_model: root.review_model[root.review_index].note_model;
                }
            }
        }

        TabViewItem {
            index: 1;
            current-index <=> parent.current-index;
            VerticalLayout {
                spacing: Style.size.spacing;
                HorizontalLayout {
                    note-text-edit := LineEdit {
                        placeholder-text: "note-text";
                    }

                    note-context-edit := LineEdit {
                        placeholder-text: "note-context";
                    }

                    Button {
                        text: "add";
                        clicked => {
                            SlintReviewCallbacks.add_note(root.review_id_parameters, note-text-edit.text, note-context-edit.text);
                            note-context-edit.text = "";
                            note-text-edit.text = "";
                        }
                    }
                }

                HorizontalLayout {
                    LineEdit {
                        placeholder-text: "filter text";
                        edited(text) => {
                            SlintReviewCallbacks.set_notes_text_filter(root.review_id_parameters, text);
                        }
                    }

                    LineEdit {
                        placeholder-text: "filter context";
                        edited(text) => {
                            SlintReviewCallbacks.set_notes_context_filter(root.review_id_parameters, text);
                        }
                    }
                }

                ListView {
                    for note in SlintReviewCallbacks.note_ui_model(root.review_id_parameters): HorizontalLayout {
                        private property <SlintNoteIdParamters> id_parameters: {
                            review_id_parameters: root.review_id_parameters,
                            note_id: note.id,
                        };
                        height: Style.size.control-height;
                        CheckBox {
                            private property <bool> is_fixed: note.is-fixed;
                            changed is_fixed => {
                                self.checked = is_fixed;
                            }
                            checked: is_fixed;
                            toggled => {
                                SlintReviewCallbacks.change_note_is_done(id_parameters, self.checked);
                            }
                        }

                        LineEdit {
                            private property <string> note_text: note.text;
                            changed note_text => {
                                self.text = note_text;
                            }
                            text: note.text;
                            accepted(text) => {
                                SlintReviewCallbacks.change_note_text(id_parameters, text);
                            }
                        }

                        LineEdit {
                            private property <string> note_context: note.context;
                            changed note_context => {
                                self.text = note_context;
                            }
                            text: note.context;
                            accepted(text) => {
                                SlintReviewCallbacks.change_note_context(id_parameters, text);
                            }
                        }

                        Text {
                            text: note.context_type == SlintContextType.Text ? @tr("Text") : @tr("File");
                        }

                        Button {
                            text: "del";
                            clicked => {
                                SlintReviewCallbacks.delete_note(id_parameters);
                            }
                        }
                    }
                }
            }
        }
    }
}
