export global Style {
    out property <length> spacing: 4px;
    out property <length> big_spacing: 6px;
    out property <length> image_width: 20px;
    out property <length> delegate_height: 32px;
    out property <length> control_height: 30px;
    out property <length> control_width: 80px;
    out property <length> control_small_width: 50px;
    out property <length> border_width: 1px;
    out property <length> border_radius: 2px;
    out property <color> popup_background: #262525;
    out property <color> popup_border_color: #333232;
    out property <color> foreground_color: #333232;
    out property <color> background_color: #262525;
    out property <color> input_background_color: #292929;
    out property <color> highlight_color: #60cdff;
    out property <color> foreground_disabled_color: #767373;
}
