export global Style {
    out property<length> spacing: 4px;
    out property<length> big_spacing: 6px;
    out property <length> control_height: 30px;
    out property <length> control_width: 80px;
    out property <length> control_small_width: 50px;
    out property <length> border_width: 1px;
    out property <color> popup_background: #262525;
    out property <color> popup_border_color: #333232;
}
