import { Palette } from "std-widgets.slint";

export struct ColorPalette {
    disabled: color,
    selected: color,
    lines_added: color,
    lines_removed: color,
    background: color,
    hover: color,
}

export struct Font {
    menu_size: length,
    sub_section_size: length,
    config_edit: length,
}

export struct Size {
    menu_border_radius: length,
    border_radius: length,
    border_width: length,
    control_small_width: length,
    control_width: length,
    control_height: length,
    delegate_height: length,
    image_width: length,
    spacing: length,
    big_spacing: length,
    padding: length,
    tab_button_width: length,
}

export global Style {
    out property <ColorPalette> palette: {
        disabled: #767373,
        selected: Palette.color-scheme == ColorScheme.dark ? #373737 : #e8e8e8,
        lines_added: #5e8262,
        lines_removed: #B06161,
        background: Palette.color-scheme == ColorScheme.dark ? Palette.background.brighter(0.8) : Palette.background,
        hover: Palette.color-scheme == ColorScheme.dark ? Palette.background.brighter(1.4) : Palette.background.brighter(0.6),
    };
    out property <Font> font: {
        menu_size: 16px,
        sub_section_size: 12px,
        config_edit: 14px,
    };
    out property <Size> size: {
        menu_border_radius: 5px,
        border_radius: 2px,
        border_width: 1px,
        control_small_width: 50px,
        control_width: 80px,
        control_height: 32px,
        delegate_height: 32px,
        image_width: 20px,
        spacing: 4px,
        big_spacing: 6px,
        padding: 8px,
        tab_button_width: 120px,
    };
}
