import { Style } from "style.slint";

export component SubSectionText inherits Rectangle {
    in property <string> text <=> text-label.text;
    height: Style.size.control_height + 2 * Style.size.spacing;

    text-label := Text {
        x: 0;
        text: "All Notes:";
        font-weight: 700;
        font-size: Style.font.sub-section-size;
        horizontal-alignment: left;
        vertical-alignment: center;
    }
}
