import {
    Button,
    VerticalBox,
    Palette,
    HorizontalBox,
    ScrollView,
} from "std-widgets.slint";
import { Style } from "style.slint";
import { ToolButton } from "tool_button.slint";

export component TabButton inherits Rectangle {
    in property <string> tab-text;
    in property <bool> is-selected: false;
    callback clicked <=> ta.clicked;

    // border-width: root.is-selected ? 1px : 0px;
    // border-color: Palette.border;
    border-top-left-radius: 10px;
    border-top-right-radius: 10px;
    border-bottom-left-radius: ta.has-hover && !root.is-selected ? 10px : 0px;
    border-bottom-right-radius: ta.has-hover && !root.is-selected ? 10px : 0px;

    background: {
        if (ta.has-hover) {
            return Palette.control-background;
        }
        return is-selected ? Palette.control-background : #292929;
    }
    // border-color: Palette.border;
    // border-width: {
    //     if (ta.pressed) {
    //         return 1px;
    //     }
    //     return root.is-selected ? 0px : 1px;
    // }

    Text {
        text: tab-text;
    }

    ta := TouchArea { }
}

export component TabCreateButton inherits Rectangle {
    callback clicked <=> ta.clicked;

    border-top-left-radius: 10px;
    border-top-right-radius: 10px;
    border-bottom-left-radius: ta.has-hover ? 10px : 0px;
    border-bottom-right-radius: ta.has-hover ? 10px : 0px;
    background: {
        if (ta.has-hover) {
            return Palette.control-background;
        }
        // if (ta.pressed) {
        //     return Palette.background;
        // }
        // return Palette.background;
        return #292929;
        //Palette.control-background;
    }
    // border-color: Palette.border;
    // border-width: Style.size.border-width;

    Image {
        vertical-alignment: center;
        width: Style.size.image_width;
        source: @image-url("../assets/icons/add.svg");
        colorize: Palette.foreground;
    }

    ta := TouchArea { }
}

export component TabViewItem inherits Rectangle {
    in property <int> current-index;
    in property <int> index;

    visible: index == current-index;
}

export component TabView inherits Rectangle {
    in property <[string]> model;
    out property <int> current-index;
    callback request-create <=> tab-create-button.clicked;

    public function set_current_index(index: int) {
        root.current-index = index;
    }
    background: #363636;
    VerticalLayout {
        Rectangle {
            background: #292929;
            height: Style.size.control-height;
            HorizontalLayout {
                spacing: Style.size.spacing;
                alignment: start;
                if root.model.length > 0: ScrollView {
                    preferred-width: 120px * root.model.length + (root.model.length - 1) * Style.size.spacing;
                    horizontal-scrollbar-policy: always-off;
                    vertical-scrollbar-policy: always-off;
                    HorizontalLayout {
                        spacing: Style.size.spacing;
                        alignment: start;
                        for tab_text[idx] in root.model: TabButton {
                            height: Style.size.control-height;
                            width: 120px;
                            tab-text: tab_text;
                            is-selected: current-index == idx;
                            clicked => {
                                root.current-index = idx;
                            }
                        }
                    }
                }

                tab-create-button := TabCreateButton {
                    height: Style.size.control-height;
                    width: Style.size.control-small-width;
                }

                Rectangle { }
            }
        }

        Rectangle {
            @children
        }
    }
}
