name: Deploy

on:
    push:
        tags:
            - "v[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
    build-and-upload:
        strategy:
            matrix:
              platform:
                - os-name: Linux-x86_64
                  runs-on: ubuntu-24.04
                  target: x86_64-unknown-linux-musl

                - os-name: Windows-x86_64
                  runs-on: windows-latest
                  target: x86_64-pc-windows-msvc

                - os-name: macOS-x86_64
                  runs-on: macOS-latest
                  target: x86_64-apple-darwin

        runs-on: ${{ matrix.platform.runs-on }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Install Linux dependencies
              if: runner.os == 'Linux'
              run: sudo apt-get update && sudo apt-get install libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libxkbcommon-x11-dev libudev-dev libinput-dev libfontconfig-dev
            - name: Build release
              uses: houseabsolute/actions-rust-cross@v1
              env:
                SLINT_BACKEND: "winit-skia"
              with:
                command: build
                target: ${{ matrix.platform.target }}
                args: "--locked --release"
                strip: true
            - name: Publish artifacts and release
              uses: houseabsolute/actions-rust-release@v0
              with:
                executable-name: review-todo
                target: ${{ matrix.platform.target }}
